# tmux2k — source from tmux.conf after common @plugin lines, before run tpm
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'gruvbox'
set -g @tmux2k-icons-only true
set -g @tmux2k-gruvbox-bg "#d5c4a1"
