[manager]
ratio = [1, 3, 7]
sort_by = "mtime"
sort_dir_first = true
show_symlink = true

[preview]
tab_size = 2
image = true
image_ueberzug = true
image_chafa = true
image_backend = "kitty"
image_max_width = 2000
image_max_height = 1800
image_quality = 90
sixel_fraction = 10
