[[language]]
name = "cpp"
roots = ["compile_commands.json", ".git"]
indent = { tab-width = 2, unit = "  " }
auto-format = true
formatter = { command = "clang-format", args = ["--style=file"] }
diagnostic-severity = "warning"
persistent-diagnostic-sources = ["clangd"]

[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--clang-tidy",
  "--completion-style=detailed",
  "--fallback-style=google",
  # "--compile-commands-dir=build",
]
config = { fallbackFlags = ["-std=c++20"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
rulers = [120]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
