-- C++ 增强配置：导航键位、outline、inlay hints、项目配置模板
-- 依赖 LazyVim clangd extra 提供的 clangd + clangd_extensions 基础配置
return {
	-- clangd_extensions: 覆盖 opts，启用原生 inline hints
	{
		"p00f/clangd_extensions.nvim",
		opts = function(_, opts)
			opts.inlay_hints = opts.inlay_hints or {}
			opts.inlay_hints.inline = vim.fn.has("nvim-0.10") == 1
			return opts
		end,
		keys = {
			{ "<leader>cH", "<cmd>ClangdTypeHierarchy<cr>", ft = { "c", "cpp", "objc", "objcpp" }, desc = "Type Hierarchy" },
			{ "<leader>ci", "<cmd>ClangdSymbolInfo<cr>", ft = { "c", "cpp", "objc", "objcpp" }, desc = "Symbol Info" },
			{ "<leader>cA", "<cmd>ClangdAST<cr>", ft = { "c", "cpp", "objc", "objcpp" }, desc = "AST View" },
			{ "<leader>cM", "<cmd>ClangdMemoryUsage<cr>", ft = { "c", "cpp", "objc", "objcpp" }, desc = "Clangd Memory Usage" },
		},
	},

	-- call hierarchy: 通过 telescope 搜索（大型 monorepo 更实用）
	{
		"nvim-telescope/telescope.nvim",
		keys = {
			{ "<leader>cw", function() require("telescope.builtin").lsp_incoming_calls() end, ft = { "c", "cpp", "objc", "objcpp" }, desc = "Incoming Calls" },
			{ "<leader>cW", function() require("telescope.builtin").lsp_outgoing_calls() end, ft = { "c", "cpp", "objc", "objcpp" }, desc = "Outgoing Calls" },
		},
	},

	-- inlay hints toggle (Neovim 0.10+ 原生 API)
	{
		"neovim/nvim-lspconfig",
		keys = {
			{
				"<leader>ct",
				function()
					vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
				end,
				ft = { "c", "cpp", "objc", "objcpp" },
				desc = "Toggle Inlay Hints",
			},
		},
	},

	-- symbol outline: aerial.nvim 浮动窗口
	{
		"stevearc/aerial.nvim",
		dependencies = {
			"nvim-treesitter/nvim-treesitter",
			"nvim-tree/nvim-web-devicons",
		},
		ft = { "c", "cpp", "objc", "objcpp", "go", "python", "lua", "rust" },
		keys = {
			{ "<leader>co", "<cmd>AerialToggle float<cr>", desc = "Symbol Outline (float)" },
		},
		opts = {
			backends = { "lsp", "treesitter" },
			layout = {
				default_direction = "float",
			},
			float = {
				border = "rounded",
				max_height = 0.6,
				max_width = 0.4,
			},
			filter_kind = {
				"Class",
				"Constant",
				"Constructor",
				"Enum",
				"Function",
				"Interface",
				"Method",
				"Module",
				"Namespace",
				"Property",
				"Struct",
			},
			keymaps = {
				["q"] = "actions.close",
				["<ESC>"] = "actions.close",
			},
		},
	},

	-- :NewClangdConfig 命令: 生成 .clangd 项目配置模板
	{
		"neovim/nvim-lspconfig",
		init = function()
			vim.api.nvim_create_user_command("NewClangdConfig", function()
				local config_path = vim.fn.getcwd() .. "/.clangd"
				if vim.fn.filereadable(config_path) == 1 then
					vim.notify(".clangd already exists, skipping", vim.log.levels.WARN)
					return
				end
				local content = [[# .clangd — generated by dotfiles nvim config
# 放在 CMake 项目根目录 (与 CMakeLists.txt 同级)
# 根据项目实际情况调整 CompilationDatabase 路径

CompileFlags:
  CompilationDatabase: build
  # 如果你的编译器有特殊路径:
  # Compiler: /usr/bin/clang++

Diagnostics:
  Suppress:
    - pp_file_not_found              # monorepo 外部依赖头文件找不到
    - drv_unknown_argument           # GCC 专有 flag，clangd 不认识
  UnusedIncludes: Strict             # IWYU 严格模式 (可改为 None 关闭)
  ClangTidy:
    Remove:
      - modernize-use-trailing-return-type
      - readability-magic-numbers
      - readability-identifier-length

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  Designators: Yes

Hover:
  ShowAKA: Yes                       # 显示 typedef/using 的底层类型

Index:
  Background: Build
  StandardLibrary: Yes

Completion:
  AllScopes: No                      # 只提示当前可访问的符号
]]
				local f = io.open(config_path, "w")
				if f then
					f:write(content)
					f:close()
					vim.notify("Generated .clangd at " .. config_path, vim.log.levels.INFO)
				else
					vim.notify("Failed to write .clangd", vim.log.levels.ERROR)
				end
			end, {})
		end,
	},
}
